
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Src/DSInternals.DataStore/DSInternals.DataStore.csproj'
    feedsToUse: 'select'
    vstsFeed: '93a639f4-b1bc-44b8-bda1-a7ec880b3dbe'
- task: VSBuild@1
  inputs:
    solution: 'Src/DSInternals.DataStore/DSInternals.DataStore.csproj'
    platform: 'x86'
    configuration: 'release'



